Neo4j REST API是一个真正的RESTful接口，使用超媒体连接为用户提供操作权限控制，就像连接。超媒体是一个动态接口类型，声明式结构（语义标记）是用来告之客户端及时的下一个合法选择。
警告
RESTful APIs 无法模仿静态接口，像WSDL或WADL描述语言。
而对于一些用例，开发人员希望使用WADL描述Neo4j REST API,特别希望使用这样的工具
在这种情况下，WADL生成将被可用，当你在neo4j.properties添加到你的服务器的文件中
unsupported_wadl_generation_enabled=true
警告
WADL不是一个官方支持Neo4j服务器API，因为WADL是不够表达来捕捉前在交互客户及可以驱动与neo4j服务器。预计WADL这样的描述是不完整的，在某些情况下相互独立整整的API。在任何情况下WADL的REST API描述不同，应该考虑更加权威的REST API。在neo4j的发布周期总，WADL生成可以撤回。


